version: '3.4'

services:
  api:
    build: .
    container_name: api
    ports:
      - "5000:80"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    